#!/bin/sh
[ $(id -u) -eq 0 ] || exec sudo $0 "$@"
exec >> /home/user/xxx
echo net-connect $(date) $@

until ip ro | grep default ; do echo no default route yet...; sleep 1; done
sleep 1
ip r a $(ip r|sed -ne "s/default/212.13.216.0\/24/p")
if ps -ef|grep openvpn -q; then
  killall -USR1 openvpn
else
  (cd /etc/openvpn; openvpn --config client-tramp-n900.conf --daemon;)
fi

ip r | grep 212.13.216.0 || echo route vanished
