#!/bin/sh
source $(dirname $0)/ds-common
all2log

echo powersave > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
kernel-config limits 125 500
[ -f /tmp/ds-unlocked.lock ] && rm -f /tmp/ds-unlocked.lock
