#!/bin/sh
[ $(id -u) -eq 0 ] || exec sudo $0 "$@"

if ([ ! -f "/sys/class/power_supply/bq27200-0/temp" ]); then
  cmd="modprobe bq27x00_battery"
  [ $(id -u) -eq 0 ] || cmd="sudo $cmd"
  $cmd
fi
T=$(cat /sys/class/power_supply/bq27200-0/temp)
N=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq)
X=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq)
echo $T / $(($N/1000))-$(($X/1000))


